name: DrMarkWeinberg
favicon: null
layout_spectrum: 0.7829251266084611
typography_spectrum: 0.9422890746500343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45168062928132713
  lightness: 0.9669731366448104
  saturation: 0.498199058463797
  rhythmicContrast: 0.5272287842817605
purpose: []
